// <auto-generated />
namespace SponsorAnAFSer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SyncWithWSDefs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SyncWithWSDefs));
        
        string IMigrationMetadata.Id
        {
            get { return "201301122222218_SyncWithWSDefs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
