// <auto-generated />
namespace SponsorAnAFSer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RenameField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameField));
        
        string IMigrationMetadata.Id
        {
            get { return "201301091817344_RenameField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
