// <auto-generated />
namespace SponsorAnAFSer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AreaTeam : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AreaTeam));
        
        string IMigrationMetadata.Id
        {
            get { return "201302140219383_AreaTeam"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
